import React from "react";
import Header from "./Header";
import Head from "next/head";
import styles from "@/styles/Home.module.scss";

interface LayoutProps {
  children: React.ReactNode;
}

const Layout = (props: LayoutProps) => {
  return (
    <>
      <Head>
        <title>Kenny's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {props.children}
    </>
  );
};

export default Layout;
